name: Android Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup Android
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        script: emulator -avd test -no-audio -no-window
        wait-for-emulator: true
        wait-for-boot: true

    - name: Build and run tests
      run: |
        ./gradlew assembleDebug assembleAndroidTest
        ./gradlew connectedAndroidTest
